config/routes.rb
Rails.application.routes.draw do
  root 'cars#index'

  resources :cars do
    member do
      get 'claim' => 'cars#claim'
    end
    
    collection do
      # stuff for all cars; e.g. wash
    end
  end

  resources :users,
    only: [:create, :new],
    path_names: { new: 'signup'}
  
  get 'my_cars' => 'users#my_cars'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  private
  
  def current_user
    @user ||= User.find(session[:id]) if session[:id]
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:edit, :update, :claim]

  def index
    @cars = Car.where(user_id: nil).all
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def claim
    @car.user = current_user
    if @car.save
      redirect_to root_path,
        notice: "#{@car.make} #{@car.model} has been moved to your inventory."
    end
  end

  #  def update
  #    @car.update(car_params)
  #    redirect_to cars_path,
  #      notice: "#{@car.year} #{@car.make} #{@car.model} updated"
  #  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to cars_path,
        notice: "#{@car.year} #{@car.make} #{@car.model} created"
    end
  end

  # PUT/PATCH /cars/1
  def update
    if @car.update(car_params)
      redirect_to cars_path,
        notice: "#{@car.year} #{@car.make} #{@car.model} updated"
    end
  end

  private

  private
  def car_params
    params.require(:car).permit(:make, :year, :model, :price)
  end

  def find_car
    @car = Car.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:id] = user.id
      redirect_to root_path,
        notice: "Welcome back #{user.first_name}"
    else
      flash[:error] = 'Invalid email or password'
      render :login
    end
  end
  
  def destroy
    if user = current_user
      session[:id] = nil
      redirect_to root_path,
        notice: "#{user.email} has been logged out."
    end
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:id] = @user.id
      redirect_to root_path,
        notice: "Thank you for signing up #{@user.first_name.titlecase}"
    else
      render :new
    end
  end

  def my_cars
    @user = User.find(current_user.id)
    @my_cars = @user.cars
  end
  
  private

  def user_params
    params.require(:user).permit(:first_name, :last_name,
      :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |form| %>
  <p>
    <%= form.label :make %>
    <%= form.text_field :make %>
  </p>
  <p>
    <%= form.label :model %>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :year %>
    <%= form.text_field :year %>
  </p>
  <p>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </p>

  <%= form.submit %>
<% end %>

app/views/cars/edit.html.erb
<h2>Edit Car</h2>

<%= render 'form' %>

app/views/cars/index.html.erb
<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Price</th>
  </tr>

  <% @cars.each do |car| %>
    <tr id="<%= dom_id(car) %>">
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= number_to_currency(car.price) %></td>
      <td><%= link_to('Edit', edit_car_path(car))%></td>
      <td><%= link_to('Claim', claim_car_path(car))%></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render 'form' %>

app/views/layouts/_authentication.html.erb
<% if current_user %>
  Signed in as <%= current_user.email %>
  <%= link_to 'My Cars', my_cars_path %>
  <%= link_to 'Logout', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Signup', new_user_path %>
  <%= link_to 'Login', login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/authentication' %>

<% flash.each do |message_type, message| %>
  <div class="<%= message_type %>">
    <%= message %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>
  <p>
    <%= form.label :first_name, 'First Name' %>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name, 'Last Name' %>
    <%= form.text_field :last_name %>
  </p>
  <p>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.text_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation, 'Password Confirmation' %>
    <%= form.text_field :password_confirmation %>
  </p>

  <%= form.submit 'Signup' %>
<% end %>

app/views/users/my_cars.html.erb
<h2>Cars claimed by <%= "#{@user.first_name} #{@user.last_name}" %> </h2>

<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Price</th>
  </tr>

  <% @my_cars.each do |car| %>
    <tr id="<%= dom_id(car) %>">
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= number_to_currency(car.price) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h2>Signup</h2>

<%= render 'form' %>

<%= link_to 'Back', root_path %>